const db = require("../models/database");

const Campers = db.shiftCampers;
const RawCampers = db.campers;
const ShiftData = db.shiftData;
const Child = db.newChildren;

const exists = async (model, entryId) => {
  const entry = await model.findByPk(entryId);
  return !!entry;
};

const addCamper = async (shift, name) => {
  try {
    await Campers.findOrCreate({
      where: {
        shift: shift,
        name: name,
      },
      defaults: {
        shift: shift,
        name: name,
      },
    });
    return true;
  } catch (err) {
    console.log(err);
    return false;
  }
};

const editNotes = async (id, note) => {
  if (!(await exists(Child, id))) return false;
  try {
    await Child.update({ notes: note }, { where: { id: id } });
    return true;
  } catch (err) {
    console.log(err);
    return false;
  }
};

const editTent = async (entryId, tentNr) => {
  if (!(await exists(ShiftData, entryId))) return false;
  try {
    await ShiftData.update({ tentNr }, { where: { id: entryId } });
    return true;
  } catch (e) {
    console.log(e);
    return false;
  }
};

exports.addAll = async (req, res) => {
  const campers = await RawCampers.findAll({
    where: { isRegistered: true },
  });

  campers.forEach((camper) => addCamper(camper["shift"], camper["name"]));
  res.status(200).end();
};

// === Internal API for the router. ===

exports.addCamper = async (req, res) => {
  if (await addCamper(req.body.shift, req.body.name)) res.status(201).end();
  else res.status(400).end();
};

exports.updateNote = async (req, res) => {
  if (await editNotes(req.body.id, req.body.notes)) res.status(201).end();
  else res.status(400).end();
};

exports.updateTent = async (entryId, tentNr) => {
  return await editTent(entryId, tentNr);
};

// Fetch information about tent rosters.
// Return an array of tent rosters and an array of kids without tents.
// Tent rosters are arrays of tent member objects.
exports.getTents = async (shiftNr) => {
  let tentData;

  // Get all tent member entries for the given shift.
  try {
    tentData = await ShiftData.findAll({ where: { shiftNr: shiftNr } });
    if (!tentData) return null;
  } catch (e) {
    console.error(e);
    return null;
  }

  // Create and initialise the return object.
  const resObj = { tents: [], noTent: [] };
  for (let i = 0; i < 10; ++i) resObj.tents[i] = [];

  // Store the promises generated by async DB calls.
  const fetchPromises = [];

  // Flag errors within the async wrapper function.
  let error = false;

  // Fetch the child associated with a tent member entry
  // and populate the return object.
  const handleChild = async (tentEntry) => {
    let child;

    try {
      child = await tentEntry.getChild();
    } catch (e) {
      console.error(e);
      error = true;
      return;
    }

    const tentNr = tentEntry.tentNr;

    if (tentNr)
      resObj.tents[tentNr - 1].push({ id: tentEntry.id, name: child.name });
    else resObj.noTent.push({ id: tentEntry.id, name: child.name });
  };

  tentData.forEach((tentEntry) => {
    if (!error) fetchPromises.push(handleChild(tentEntry));
  });

  await Promise.all(fetchPromises);

  if (error) return null;
  return resObj;
};
